[package]
name = "htb"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "s"
lto = true
panic = "abort"
strip = true

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
attohttpc = "0.23.1"
json = "0.12.4"